### ISSUE TITLE
Manual Image advance / Slideshow

### ISSUE THREAD

**Issue by mkammes** [NickWaterton/samsung-tv-ws-api#6]
As I peruse your fantastic repo, I'm realizing what I'm trying to do may not be possible.

Is there any function to programmatically advance (or reverse) a slideshow image(s)? I then tie this to manual triggers, such as a keypress. Doing this via the remote loads an undesireable on-screen display.

The use case is to use this as a presentation aid. Sure, I can switch to video mode and simply extend my laptop screen, but the art mode look is what I'd like to retain 24-7.

I see there are ways (and other repos) to set the slideshow change time interval or based on seasons - but that's somewhat pre-defined.
Uploading a new image and displaying it each time is an option, but that process takes several seconds.

Does the API allow for the functionality I'm looking for? Frame 2024 model.

Thanks!

**Comment by mkammes** [comment]
I was able to hack this together. It's not pretty, and I'm still struggling with setting the correct order of images (navigating), but....each time you run the script the art changes to the next image in the slideshow. And no onscreen displays.

```
from samsungtvws import SamsungTVWS
import logging
import json
import time

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def get_next_image_id(current_id):
    """Define the sequence of images to cycle through"""
    sequence = ["MY_F0102", "MY_F0103", "MY_F0101", "MY_F0007", "MY_F0006"]
    
    try:
        current_index = sequence.index(current_id)
        next_index = (current_index + 1) % len(sequence)
        return sequence[next_index]
    except ValueError:
        # If current_id not in sequence, start from beginning
        return sequence[0]

def advance_frame_image(host, port=8002):
    """Advance to the next image in the sequence"""
    try:
        tv = SamsungTVWS(host, port)
        art = tv.art()
        
        # Get current image
        current = art.get_current()
        current_id = current.get('content_id')
        
        # Get next image ID
        next_id = get_next_image_id(current_id)
        
        # Select next image
        result = art.select_image(next_id)
        logger.info(f"Advanced from {current_id} to {next_id}")
        return True
        
    except Exception as e:
        logger.error(f"Error advancing image: {e}")
        return False

if __name__ == '__main__':
    TV_IP = "192.168.1.xxx"
    success = advance_frame_image(TV_IP)
    print(f"Image advance {'successful' if success else 'failed'}")
```

**Comment by NickWaterton** [comment]
@mkammes 
It’s probably doable. What kind of input are you looking for? A keypress on a keyboard for example (that’s the easiest).

Your code isn’t bad, I can probably put something together for you tomorrow based on what you posted.

I’ll ping you when I have something to try out.

**Comment by mkammes** [comment]
I was planning on adding this to home assistant and triggering a NEXT and PREVIOUS command with the appropriate keyless. At the most basic, a NEXT keypress.

My concern is the file naming, which I'm still researching to make this script dynamic.

Thank you - happy to send some coffee money your way!

**Comment by NickWaterton** [comment]
Try this:
```
#!/usr/bin/env python3
import argparse
import logging
import os
import sys

sys.path.append("../")

from samsungtvws import SamsungTVWS, exceptions, __version__

def parseargs():
    # Add command line argument parsing
    parser = argparse.ArgumentParser(description='Example art Samsung Frame TV Version: {}'.format(__version__))
    parser.add_argument('ip', action="store", type=str, default=None, help='ip address of TV (default: %(default)s))')
    parser.add_argument('-t','--token_file', action="store", type=str, default="token_file.txt", help='default token file to use (default: %(default)s))')
    parser.add_argument('-D','--debug', action='store_true', default=False, help='Debug mode (default: %(default)s))')
    return parser.parse_args()
    
class Slideshow:
    input_chars = ['n', 'p']
    
    def __init__(self, args):
        self.log = logging.getLogger('Main.'+__class__.__name__)
        # Normal constructor (will ask for connection every time on 2024 TV's)
        self.tv = SamsungTVWS(host=args.ip, port=8002)
        
        # Autosave token to file
        #self.tv = SamsungTVWS(host=args.ip, port=8002, token_file=args.token_file)
        self.sequence = self.get_tv_content()
        self.current = self.get_current_art()
        try:
            self.index = self.sequence.index(self.current)
            self.input_loop()
        except ValueError as e:
            self.log.critical('Current art not found: {}'.format(e))
        
    def input_loop(self):
        '''
        gets next character from keyboard
        n = next, p = previous, q = quit
        '''
        char = None
        while char != 'q' :
            char = input('n,p,q >> ').lower()
            if char in self.input_chars:
                self.advance_frame_image(char)
        
    def get_tv_content(self, category='MY-C0002'):
        '''
        gets content_id list of category - either My Photos (MY-C0002) or Favourites (MY-C0004) from tv
        use 10 second timeout in case tv has a lot of content (tv.art(10))
        '''
        try:
            result = [v['content_id'] for v in self.tv.art().available(category)]
        except AssertionError:
            self.log.warning('failed to get contents from TV')
            result = None
        return result
        
    def get_current_art(self):
        '''
        gets content_id for current art
        '''
        try:
            art = self.tv.art().get_current()
            result = art['content_id']
        except AssertionError:
            self.log.warning('failed to get current art from TV')
            result = None
        return result
        
    def advance_frame_image(self, char='n'):
        '''
        Next or previous image in the sequence
        '''
        try:
            new_index = self.index+1 if char == 'n' else self.index-1
            # wrap around
            new_index = new_index % len(self.sequence)
            self.log.info('current index: {} new index: {} max: {}'.format(self.index, new_index, len(self.sequence)-1))
            next_id = self.sequence[new_index]
            # Select new image
            self.tv.art().select_image(next_id)
            self.log.info(f"Advanced from {self.sequence[self.index]} to {next_id}")
            self.index = new_index
            return True
            
        except Exception as e:
            self.log.error(f"Error changing image: {e}")
            return False

def main():
    args = parseargs()
    logging.basicConfig(format='%(asctime)s %(levelname)s %(module)s %(funcName)s %(message)s',
                        level=logging.DEBUG if args.debug else logging.INFO)
    logging.debug('debug mode')
    Slideshow(args)


if __name__ == '__main__':
    main()
```
You have to press enter after `n` or `p` or `q` because that's the way input works on Python, but you get the idea.

**Comment by mkammes** [comment]
Thank you so much, this is working, and I'll start porting this over for use within Home Assistant.

I am struggling to understand the auto-naming the Frame does for images and in what order these images are prioritized.  I see "MY_", (with both "C" and "F" followed by numbers) "SAM" (I assume Samsung Stock images) Are there rules of thumb to follow?  I want to ensure if I upload, let's say, 20 images, that they are auto-named correctly and in play sequence with your script.

Thanks again!

**Comment by NickWaterton** [comment]
Thanks for the support!

The Samsung naming convention, as far as I can tell is:
* MY_XXXX Uploaded files, ie “My Photos”
* SAM_XXXX Samsung art store files.

I don’t know what C or F means in uploaded files, probably not significant.

There are also two categories, MY-C0002 which is My Photos, and MY-C0004 which is Favourites. You can select either in `get_tv_content()`, the default is MY-C0002.

I use Home Assistant for some things, it’ll be interesting to see how you integrate this.
Merry Christmas!

**Comment by mkammes** [comment]
Hey Nick!

I used this extensively for a few weeks for a project. It works great. It then sat...until now.

Now the Frame fails to advance or reverse images in Art Mode, and the "SamsungTvRemote (Allow/Deny/Close)" alert pops up after every frame advance/frame reverse command.

Has something changed?  Thanks!

**Comment by NickWaterton** [comment]
You have a token file problem. The TV now requires a token for art api access. Make sure you are passing the right token file to the constructor.

So, make sure, you have the latest version of the library. Delete the ‘token_file.txt‘ file, and try the connection again. Accept the connection on the TV, and it should save the new token, and start working again.

You may have to delete the device on the TV as well if it got too messed up.

**Comment by mkammes** [comment]
Thanks for the quick reply!

The library is updated, and the device is deleted. The Remote "Allow/Deny/Close" alert persists on the TV, and no commands are accepted (previous image, next image)

Has something changed with token handling?  My system is now having all sorts of problems with writing the token into a file successfully and then retrieving it.

I see someone else is asking for a Home Assistant version, too ;-)

**Comment by NickWaterton** [comment]
I've been looking at HA, but I use Openhab (wrote the samsungtv binding for it), so HA is a bit of a learning curve...

As to the token handling, I haven't changed anything in the library, but Samsung changed the firmware on the TV to _require_ a token for the art websocket - which it didn't before.

So, it's possible that your program was simply not using the token before, and it didn't matter - but now it does.

The behavior you are describing (constantly asking to Allow/Deny etc) is what happens when you try to connect to the art websocket without a token now (but clicking on "Allow" does not actually allow the connection).

So, there is something about your program that is not saving/loading the token file.

Have you _installed_ the library properly?
What location are you using for the `token_file.txt` file? The default is wherever you are running the script from, but it may be different on your PC set up - and Mac's are finnicky.

Also, what happens when you run  `async_art_simple.py` from the example folder with Debug on?

Can you post your code, and I can take a look, see if I can spot the problem.

**Comment by mkammes** [comment]
Thanks for the offer!

Summary of where I'm at:

- **Model:** QN32LS03CBFXZA (32" The Frame)
- **IP:** 192.168.1.107
- **State:** In Art Mode (displaying artwork)
- **Library:** samsungtvws 2.7.2

GET /api/v2/ HTTP/1.1" 200 1362
FrameTVSupport: true
TokenAuthSupport: true
PowerState: on

WS url wss://192.168.1.107:8002/api/v2/channels/com.samsung.art-app?name=U2Ftc3VuZ1R2UmVtb3Rl&token=36189133

> GET /api/v2/channels/com.samsung.art-app?token=36189133 HTTP/1.1
> Host: 192.168.1.107:8002
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Key: z6hPp0kkt4jIvYPHzeetzg==
> Sec-WebSocket-Version: 13
> User-Agent: Python/3.12 websockets/15.0.1

< HTTP/1.1 101 Switching Protocols
< Upgrade: WebSocket
< Connection: Upgrade

< TEXT '{"event":"ms.channel.timeOut"}'
Processing API response: {"event":"ms.channel.timeOut"}
websocket event: {'event': 'ms.channel.timeOut'}
Connection closed.

```
2025-11-23 13:46:05,564 DEBUG async_art_simple main debug mode
2025-11-23 13:46:05,564 INFO async_art_simple main opening art websocket with token
2025-11-23 13:46:05,565 DEBUG connection __init__ version: 3.0.3
2025-11-23 13:46:05,565 DEBUG connection __init__ version: 3.0.3
2025-11-23 13:46:05,565 DEBUG connection __init__ version: 3.0.3
2025-11-23 13:46:05,568 DEBUG connectionpool _new_conn Starting new HTTPS connection (1): 192.168.1.107:8002
/homeassistant/samsung_tvws_venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.107'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2025-11-23 13:46:05,616 DEBUG connectionpool _make_request https://192.168.1.107:8002 "GET /api/v2/ HTTP/1.1" 200 1362
2025-11-23 13:46:05,617 DEBUG helper process_api_response Processing API response: {"device":{"EdgeBlendingSupport":"false","EdgeBlendingSupportGroup":"0","FrameTVSupport":"true","GamePadSupport":"true","ImeSyncedSupport":"true","Language":"en_US","OS":"Tizen","PowerState":"on","TokenAuthSupport":"true","VoiceSupport":"true","WallScreenRatio":"-1","WallService":"false","countryCode":"US","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:29d80c4d-8510-4bfe-b26d-3e5dde825c0a","firmwareVersion":"Unknown","id":"uuid:29d80c4d-8510-4bfe-b26d-3e5dde825c0a","ip":"192.168.1.107","model":"23_KANTSU2E_FTV_OS80","modelName":"QN32LS03CBFXZA","name":"32&quot; The Frame","networkType":"wireless","resolution":"1920x1080","smartHubAgreement":"true","ssid":"f6:92:bf:5c:f3:2b","type":"Samsung SmartTV","udn":"uuid:29d80c4d-8510-4bfe-b26d-3e5dde825c0a","wifiMac":"28:E6:A9:2A:15:1E"},"id":"uuid:29d80c4d-8510-4bfe-b26d-3e5dde825c0a","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"32&quot; The Frame","remote":"1.0","type":"Samsung SmartTV","uri":"https://192.168.1.107:8002/api/v2/","version":"2.0.25"}

2025-11-23 13:46:05,620 DEBUG async_connection open WS url wss://192.168.1.107:8002/api/v2/channels/com.samsung.art-app?name=U2Ftc3VuZ1R2UmVtb3Rl&token=36189133
2025-11-23 13:46:05,624 DEBUG protocol __init__ = connection is CONNECTING
2025-11-23 13:46:05,645 DEBUG client write_http_request > GET /api/v2/channels/com.samsung.art-app?name=U2Ftc3VuZ1R2UmVtb3Rl&token=36189133 HTTP/1.1
2025-11-23 13:46:05,647 DEBUG client write_http_request > Host: 192.168.1.107:8002
2025-11-23 13:46:05,647 DEBUG client write_http_request > Upgrade: websocket
2025-11-23 13:46:05,647 DEBUG client write_http_request > Connection: Upgrade
2025-11-23 13:46:05,648 DEBUG client write_http_request > Sec-WebSocket-Key: z6hPp0kkt4jIvYPHzeetzg==
2025-11-23 13:46:05,649 DEBUG client write_http_request > Sec-WebSocket-Version: 13
2025-11-23 13:46:05,649 DEBUG client write_http_request > Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
2025-11-23 13:46:05,649 DEBUG client write_http_request > User-Agent: Python/3.12 websockets/15.0.1
2025-11-23 13:46:05,654 DEBUG client read_http_response < HTTP/1.1 101 Switching Protocols
2025-11-23 13:46:05,655 DEBUG client read_http_response < Upgrade: WebSocket
2025-11-23 13:46:05,656 DEBUG client read_http_response < Connection: Upgrade
2025-11-23 13:46:05,656 DEBUG client read_http_response < Sec-WebSocket-Accept: UjsHgb+japagU+LbbRcGHXNfFVc=
2025-11-23 13:46:05,657 DEBUG protocol connection_open = connection is OPEN
2025-11-23 13:46:09,716 DEBUG protocol read_frame < TEXT '{"event":"ms.channel.timeOut"}\n' [31 bytes]
2025-11-23 13:46:09,716 DEBUG helper process_api_response Processing API response: {"event":"ms.channel.timeOut"}

2025-11-23 13:46:09,716 DEBUG connection _websocket_event SamsungTVWS websocket event: {'event': 'ms.channel.timeOut'}
2025-11-23 13:46:09,716 DEBUG async_connection close Connection closed.
2025-11-23 13:46:09,716 DEBUG async_connection open connection not accepted on TV, or token missing/incorrect
2025-11-23 13:46:09,782 DEBUG protocol connection_lost = connection is CLOSED
Traceback (most recent call last):
  File "/homeassistant/samsung-tv-ws-api/example/async_art_simple.py", line 75, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/homeassistant/samsung-tv-ws-api/example/async_art_simple.py", line 29, in main
    await tv.start_listening()
  File "/homeassistant/samsung-tv-ws-api/samsungtvws/async_art.py", line 109, in start_listening
    await self.open()
  File "/homeassistant/samsung-tv-ws-api/samsungtvws/async_art.py", line 86, in open
    await super().open()
  File "/homeassistant/samsung-tv-ws-api/samsungtvws/async_connection.py", line 78, in open
    raise exceptions.ConnectionFailure(response)
samsungtvws.exceptions.ConnectionFailure: {'event': 'ms.channel.timeOut'}
```

As Home Assistant OS (HAOS) needs to have some care taken so non-HAOS libraries persist after restart, I have a venv with the required libraries.

For testing, I also reverted to your manual_slideshow.py code to eliminate anything I had done.

```
#!/usr/bin/env python3
import argparse
import logging

from samsungtvws import SamsungTVWS, exceptions, __version__

def parseargs():
    # Add command line argument parsing
    parser = argparse.ArgumentParser(description='Example art Samsung Frame TV Version: {}'.format(__version__))
    parser.add_argument('ip', action="store", type=str, default=None, help='ip address of TV (default: %(default)s))')
    parser.add_argument('-t','--token_file', action="store", type=str, default="token_file.txt", help='default token file to use (default: %(default)s))')
    parser.add_argument('-D','--debug', action='store_true', default=False, help='Debug mode (default: %(default)s))')
    return parser.parse_args()
    
class Slideshow:
    input_chars = ['n', 'p']
    
    def __init__(self, args):
        self.log = logging.getLogger('Main.'+__class__.__name__)
        # Normal constructor (will ask for connection every time on 2024 TV's)
        self.tv = SamsungTVWS(host=args.ip, port=8002)
        
        # Autosave token to file
        #self.tv = SamsungTVWS(host=args.ip, port=8002, token_file=args.token_file)
        if self.get_tv_content():
            self.input_loop()
        
    def input_loop(self):
        '''
        gets next character from keyboard
        n = next, p = previous, q = quit
        '''
        char = None
        while char != 'q' :
            char = input('n,p,q >> ').lower()
            if char in self.input_chars:
                if not self.advance_frame_image(char):
                    break
        
    def get_tv_content(self, category='MY-C0002'):
        '''
        gets content_id list of category - either My Photos (MY-C0002) or Favourites (MY-C0004) from tv
        use 10 second timeout in case tv has a lot of content (tv.art(10))
        gets content_id for current art
        and current index
        '''
        try:
            self.sequence = [v['content_id'] for v in self.tv.art(10).available(category)]
            self.current = self.tv.art().get_current()['content_id']
            self.index = self.sequence.index(self.current)
            return True
        except (AssertionError, ValueError) as e:
            self.log.warning('failed to get contents from TV {}'.format(e))
        return False
        
    def advance_frame_image(self, char='n'):
        '''
        Next or previous image in the sequence
        '''
        try:
            new_index = self.index + (1 if char == 'n' else -1)
            # wrap around
            new_index = new_index % len(self.sequence)
            self.log.debug('current index: {} new index: {} max: {}'.format(self.index, new_index, len(self.sequence)-1))
            next_id = self.sequence[new_index]
            # Select new image
            self.tv.art().select_image(next_id)
            self.log.info(f"Advanced from {self.sequence[self.index]} to {next_id}")
            self.index = new_index
            return True
        except Exception as e:
            self.log.error(f"Error changing image: {e}")
        return False

def main():
    args = parseargs()
    logging.basicConfig(format='%(asctime)s %(levelname)s %(module)s %(funcName)s %(message)s',
                        level=logging.DEBUG if args.debug else logging.INFO)
    logging.debug('debug mode')
    Slideshow(args)


if __name__ == '__main__':
    main()
```

I also archived all of this and re-cloned your repo and dependencies and put them in a new venv. The same errors persist.

Thanks Nick!

**Comment by NickWaterton** [comment]
@mkammes 

What that is telling me is that you are sending the wrong token.

I don’t know where you are getting the token from, but it’s incorrect.

You have to delete the `token_file.txt` wherever it is, or whatever you have called it, in order to trigger the library to get a new token.

What is supposed to happen then, if you use an art API call, is that the library makes a connection to the _remote_ websocket (because that’s the only websocket that can issue a token) - you have 30 seconds to click in “accept”, and a new token is returned and saved in the file.

Then the art websocket connect using the new, saved token.

This is not happening in your log, the connection is being made with a token obtained from somewhere - and it’s incorrect - so it doesn’t work.

Hope this explains what is going on. You need to fine the file storing the token, and delete it.

**Comment by mkammes** [comment]
It looks like I still wasn't getting the right token. I've since remedied that, and things are all well now. Thanks!
